import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"
import Header from "./components/Header";
import Sidebar from './components/Sidebar';

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={montserrat.variable}>
        <Sidebar>
          <Header />
          {children}
        </Sidebar>
        <Navbar />
      </body>
    </html>
  );
}
